// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCauf_crclkQOmncqwr7uQxuYyoUiNS9U4',
    appId: '1:219679248595:web:24c4aac0f0be0745168426',
    messagingSenderId: '219679248595',
    projectId: 'ucgul-5cbec',
    authDomain: 'ucgul-5cbec.firebaseapp.com',
    storageBucket: 'ucgul-5cbec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCauf_crclkQOmncqwr7uQxuYyoUiNS9U4',
    appId: '1:219679248595:android:24c4aac0f0be0745168426',
    messagingSenderId: '219679248595',
    projectId: 'ucgul-5cbec',
    storageBucket: 'ucgul-5cbec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCauf_crclkQOmncqwr7uQxuYyoUiNS9U4',
    appId: '1:219679248595:ios:24c4aac0f0be0745168426',
    messagingSenderId: '219679248595',
    projectId: 'ucgul-5cbec',
    storageBucket: 'ucgul-5cbec.firebasestorage.app',
    iosBundleId: 'com.program.ucgul1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCauf_crclkQOmncqwr7uQxuYyoUiNS9U4',
    appId: '1:219679248595:ios:24c4aac0f0be0745168426',
    messagingSenderId: '219679248595',
    projectId: 'ucgul-5cbec',
    storageBucket: 'ucgul-5cbec.firebasestorage.app',
    iosBundleId: 'com.program.ucgul1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCauf_crclkQOmncqwr7uQxuYyoUiNS9U4',
    appId: '1:219679248595:web:24c4aac0f0be0745168426',
    messagingSenderId: '219679248595',
    projectId: 'ucgul-5cbec',
    authDomain: 'ucgul-5cbec.firebaseapp.com',
    storageBucket: 'ucgul-5cbec.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCauf_crclkQOmncqwr7uQxuYyoUiNS9U4',
    appId: '1:219679248595:web:24c4aac0f0be0745168426',
    messagingSenderId: '219679248595',
    projectId: 'ucgul-5cbec',
    authDomain: 'ucgul-5cbec.firebaseapp.com',
    storageBucket: 'ucgul-5cbec.firebasestorage.app',
  );
}